### ISSUE TITLE
installation error qgis bucuresti

### ISSUE THREAD

**Issue by gabrielmancilla** [hotosm/oam-qgis-plugin#105]
this plugin works with qgis 3.12.3 - Bucuresti? I tried to install the OpenAerialMap-0.1-alpha.3.6 file but gave the following error message:

Impossível carregar complemento 'OpenAerialMap' Devido a um erro ao chamar o método Class Factory(). 

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead. 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\__init__.py", line 59, in classFactory
    from .oam_main import OpenAerialMap
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 743, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\oam_main.py", line 31, in 
    from PyQt4.QtCore import (QSettings,
  File "C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python\qgis\utils.py", line 741, in _import
    raise ImportError(msg)
ImportError: PyQt4 classes cannot be imported in QGIS 3.x.
Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead.

Versão do Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versão do QGIS: 3.12.3-București București, 8234261527 

Caminho do Python:
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.12/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.12\apps\Python37
C:\PROGRA~1\QGIS3~1.12\apps\Python37\Scripts
C:\Program Files\QGIS 3.12\bin\python37.zip
C:\PROGRA~1\QGIS3~1.12\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib
C:\Program Files\QGIS 3.12\bin
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.12\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DsgTools
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\Usuario\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/boto-2.38.0
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/filechunkio-1.6
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/requests-2.7.0
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/geopy-1.11.0
.
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/boto-2.38.0
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/filechunkio-1.6
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/requests-2.7.0
C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenAerialMap\ext_libs/geopy-1.11.0

**Comment by yojiyojiyoji** [comment]
Actually, this plugin doesn't support QGIS 3.x., since the project is being suspended.
(To be honest, I was surprised that it worked on Ver. 3.12.3)
If we re-start the project, we will let you know about it, but at the moment, we have no plan to do it.

**Comment by koyo-nic** [comment]
@yojiyojiyoji @gabrielmancilla  I have managed to port the whole plugin to V3 api but still having some small errors when querying and uploading. Using QGIS Pi. Test in Ubuntu 18.04 env. All widgets are loaded succesfully besides a call to the search dialog. i'd be happy to do a pr

**Comment by koyo-jakanees** [comment]
[upgrade to qgis3 branch](https://github.com/koyo-jakanees/oam-qgis-plugin/tree/upgrade-qgis3):

**Comment by yojiyojiyoji** [comment]
@koyo-jakanees 
If you really like to use the plugin with QGIS3.x, you can try the express edition (only image search and download, no upuloader) at:
https://github.com/yojiyojiyoji/oam_qgis3_express
(For the installation, check the Makefile first. I think it would not difficult if you run it on ubuntu.)
